"""
Datos de prueba (seed) para el catálogo de medicamentos en modo memoria.

Este catálogo es solo para desarrollo y tests. Con STORAGE_BACKEND=postgresql
(video-07) los medicamentos se cargarán desde la base de datos.
"""

from decimal import Decimal

from app.domain.entities import Medication


def get_default_medications() -> list[Medication]:
    """Devuelve 10-15 medicamentos de ejemplo con todos los campos del motor de recomendaciones.
    Incluye variedad de economic_margin, indicated_symptom_labels/indicated_hypothesis_labels
    (por nombre, p. ej. "Dolor de garganta", "Faringitis leve"), age_min/age_max, allowed_sexes,
    suitable_for_pregnancy, y al menos uno sin stock.
    """
    return [
        Medication(
            id="med-1",
            name="Paracetamol 500 mg",
            category="Analgésico",
            reason="Dolor leve, fiebre",
            badge="main",
            price="3.50",
            stock="100",
            format="20 comprimidos",
            age_min=0,
            age_max=120,
            allowed_sexes=(),
            suitable_for_pregnancy=True,
            indicated_symptom_labels=("Dolor de garganta", "Fiebre leve"),
            indicated_hypothesis_labels=("Faringitis leve",),
            economic_margin=Decimal("1.20"),
        ),
        Medication(
            id="med-2",
            name="Ibuprofeno 400 mg",
            category="Antiinflamatorio",
            reason="Dolor, inflamación",
            badge="alternative",
            price="4.20",
            stock="50",
            format="30 comprimidos",
            age_min=12,
            age_max=120,
            allowed_sexes=(),
            suitable_for_pregnancy=False,
            indicated_symptom_labels=("Dolor de garganta", "Fiebre leve", "inflamación"),
            indicated_hypothesis_labels=("Faringitis leve",),
            economic_margin=Decimal("50.00"),
        ),
        Medication(
            id="med-3",
            name="Amoxicilina 500 mg",
            category="Antibiótico",
            reason="Infecciones bacterianas",
            badge="alternative",
            price="5.80",
            stock="30",
            format="21 cápsulas",
            age_min=1,
            age_max=120,
            allowed_sexes=(),
            suitable_for_pregnancy=False,
            indicated_symptom_labels=("Dolor de garganta",),
            indicated_hypothesis_labels=("Faringitis leve",),
            economic_margin=Decimal("3.50"),
        ),
        Medication(
            id="med-4",
            name="Jarabe para la tos",
            category="Antitusivo",
            reason="Tos seca",
            badge="alternative",
            price="6.20",
            stock="25",
            format="120 ml",
            age_min=2,
            age_max=120,
            allowed_sexes=(),
            suitable_for_pregnancy=False,
            indicated_symptom_labels=("Dolor de garganta",),
            indicated_hypothesis_labels=(),
            economic_margin=Decimal("1.80"),
        ),
        Medication(
            id="med-5",
            name="Spray garganta",
            category="Antiséptico local",
            reason="Dolor de garganta",
            badge="main",
            price="8.50",
            stock="40",
            format="30 ml",
            age_min=6,
            age_max=120,
            allowed_sexes=(),
            suitable_for_pregnancy=True,
            indicated_symptom_labels=("Dolor de garganta",),
            indicated_hypothesis_labels=("Faringitis leve",),
            economic_margin=Decimal("4.00"),
        ),
        Medication(
            id="med-6",
            name="Vitamina C 1 g",
            category="Suplemento",
            reason="Defensas, resfriado",
            badge="alternative",
            price="7.00",
            stock="60",
            format="20 comprimidos",
            age_min=14,
            age_max=120,
            allowed_sexes=(),
            suitable_for_pregnancy=True,
            indicated_symptom_labels=("Fiebre leve",),
            indicated_hypothesis_labels=(),
            economic_margin=Decimal("0.90"),
        ),
        Medication(
            id="med-7",
            name="Antigripal compuesto",
            category="Sintomático",
            reason="Gripe, fiebre, dolor",
            badge="alternative",
            price="5.50",
            stock="20",
            format="10 sobres",
            age_min=18,
            age_max=65,
            allowed_sexes=(),
            suitable_for_pregnancy=False,
            indicated_symptom_labels=("Dolor de garganta", "Fiebre leve"),
            indicated_hypothesis_labels=("Faringitis leve",),
            economic_margin=Decimal("2.80"),
        ),
        Medication(
            id="med-8",
            name="Paracetamol pediátrico",
            category="Analgésico",
            reason="Fiebre y dolor en niños",
            badge="alternative",
            price="4.00",
            stock="15",
            format="120 ml",
            age_min=0,
            age_max=12,
            allowed_sexes=(),
            suitable_for_pregnancy=False,
            indicated_symptom_labels=("Fiebre leve",),
            indicated_hypothesis_labels=(),
            economic_margin=Decimal("1.50"),
        ),
        Medication(
            id="med-9",
            name="Pastillas garganta mujer",
            category="Antiséptico",
            reason="Irritación de garganta",
            badge="alternative",
            price="6.00",
            stock="35",
            format="24 pastillas",
            age_min=18,
            age_max=120,
            allowed_sexes=("Mujer",),
            suitable_for_pregnancy=True,
            indicated_symptom_labels=("Dolor de garganta",),
            indicated_hypothesis_labels=("Faringitis leve",),
            economic_margin=Decimal("2.20"),
        ),
        Medication(
            id="med-10",
            name="Complejo B inyectable",
            category="Suplemento",
            reason="Cansancio, defensas",
            badge="alternative",
            price="12.00",
            stock="0",
            format="5 ampollas",
            age_min=18,
            age_max=120,
            allowed_sexes=(),
            suitable_for_pregnancy=False,
            indicated_symptom_labels=("Fiebre leve",),
            indicated_hypothesis_labels=(),
            economic_margin=Decimal("5.00"),
        ),
        Medication(
            id="med-11",
            name="Caramelos eucalipto",
            category="Demulcente",
            reason="Alivio garganta",
            badge="alternative",
            price="2.50",
            stock="80",
            format="1 blister",
            age_min=None,
            age_max=None,
            allowed_sexes=(),
            suitable_for_pregnancy=True,
            indicated_symptom_labels=("Dolor de garganta",),
            indicated_hypothesis_labels=("Faringitis leve",),
            economic_margin=Decimal("0.50"),
        ),
        Medication(
            id="med-12",
            name="Naproxeno 550 mg",
            category="Antiinflamatorio",
            reason="Dolor e inflamación",
            badge="alternative",
            price="4.80",
            stock="40",
            format="20 comprimidos",
            age_min=16,
            age_max=120,
            allowed_sexes=("Hombre", "Mujer"),
            suitable_for_pregnancy=False,
            indicated_symptom_labels=("Dolor de garganta",),
            indicated_hypothesis_labels=("Faringitis leve",),
            economic_margin=Decimal("2.50"),
        ),
    ]
