"""
Datos de prueba (seed) para el catálogo de medicamentos en modo memoria.

Este catálogo es solo para desarrollo y tests. Con STORAGE_BACKEND=postgresql
(video-07) los medicamentos se cargarán desde la base de datos.

~100 medicamentos para síntomas comunes: dolor de garganta, fiebre, tos, cefalea,
congestión, dolor muscular, acidez, diarrea, estreñimiento, alergia, etc.
"""

from decimal import Decimal

from app.domain.entities import Medication


def _med(
    id: str,
    name: str,
    category: str,
    reason: str,
    price: str,
    stock: str,
    format: str,
    age_min: int | None,
    age_max: int | None,
    symptoms: tuple[str, ...],
    hypotheses: tuple[str, ...],
    economic_margin: str,
    allowed_sexes: tuple = (),
    suitable_for_pregnancy: bool = False,
) -> Medication:
    """Helper para construir Medication con badge por defecto (el caso de uso asigna main/alternative)."""
    return Medication(
        id=id,
        name=name,
        category=category,
        reason=reason,
        badge="main",
        price=price,
        stock=stock,
        format=format,
        age_min=age_min,
        age_max=age_max,
        allowed_sexes=allowed_sexes,
        suitable_for_pregnancy=suitable_for_pregnancy,
        indicated_symptom_labels=symptoms,
        indicated_hypothesis_labels=hypotheses,
        economic_margin=Decimal(economic_margin),
    )


def get_default_medications() -> list[Medication]:
    """Devuelve ~100 medicamentos de ejemplo para síntomas e hipótesis más comunes."""
    return [
        # --- Dolor de garganta / Faringitis (1-15) ---
        _med("med-1", "Paracetamol 650 mg", "Analgésico", "Fiebre y dolor asociado a infección respiratoria alta", "3.90", "110", "20 comprimidos", 6, 120, ("Fiebre", "Dolor de garganta", "Malestar general"), ("Faringitis", "Resfriado común", "Gripe (influenza)"), "1.30"),
        _med("med-2", "Ibuprofeno 400 mg", "Antiinflamatorio", "Dolor e inflamación de garganta con febrícula", "4.20", "55", "30 comprimidos", 12, 120, ("Dolor de garganta", "Odinofagia (dolor al tragar)", "Febrícula"), ("Faringitis", "Amigdalitis"), "2.05"),
        _med("med-3", "Flurbiprofeno 8,75 mg pastillas", "Antiinflamatorio local", "Alivio del dolor de garganta y odinofagia", "7.10", "38", "24 pastillas", 12, 120, ("Dolor de garganta", "Odinofagia (dolor al tragar)", "Ronquera (disfonía)"), ("Faringitis", "Infección respiratoria alta (IRA alta)"), "2.70"),
        _med("med-4", "Benzydamine spray garganta", "Antiinflamatorio local", "Dolor de garganta con irritación y dificultad al tragar", "9.50", "22", "30 ml", 12, 120, ("Dolor de garganta", "Odinofagia (dolor al tragar)", "Ronquera (disfonía)"), ("Faringitis", "Amigdalitis"), "3.60"),
        _med("med-5", "Pastillas miel y limón", "Demulcente", "Calma la irritación de garganta y la tos seca leve", "2.80", "95", "1 blister", 6, 120, ("Dolor de garganta", "Tos seca", "Ronquera (disfonía)"), ("Resfriado común", "Infección respiratoria alta (IRA alta)"), "0.75"),
        _med("med-6", "Hexetidina colutorio", "Antiséptico local", "Higiene orofaríngea en molestias de garganta", "5.40", "48", "200 ml", 6, 120, ("Dolor de garganta", "Odinofagia (dolor al tragar)", "Hinchazón de garganta"), ("Faringitis", "Infección respiratoria alta (IRA alta)"), "1.70"),
        _med("med-7", "Spray garganta clorhexidina", "Antiséptico local", "Alivio local en irritación de garganta", "8.20", "44", "30 ml", 6, 120, ("Dolor de garganta", "Odinofagia (dolor al tragar)", "Hinchazón de garganta"), ("Faringitis", "Amigdalitis"), "3.90"),
        _med("med-8", "Spray garganta lidocaína", "Anestésico local", "Dolor intenso de garganta con odinofagia", "7.80", "18", "15 ml", 18, 120, ("Dolor de garganta", "Odinofagia (dolor al tragar)", "Dolor localizado con presión"), ("Faringitis", "Amigdalitis"), "2.55"),
        _med("med-9", "Pastillas de salvia", "Fitoterapia", "Irritación de garganta y ronquera", "4.90", "52", "25 pastillas", 6, 120, ("Dolor de garganta", "Ronquera (disfonía)", "Afónica/pérdida de voz"), ("Infección respiratoria alta (IRA alta)", "Resfriado común"), "1.35"),
        _med("med-10", "Naproxeno 550 mg", "Antiinflamatorio", "Dolor y fiebre asociados a proceso inflamatorio", "4.80", "42", "20 comprimidos", 16, 120, ("Dolor de garganta", "Fiebre", "Dolor"), ("Faringitis", "Gripe (influenza)"), "2.60"),
        _med("med-11", "Paracetamol 1 g", "Antitérmico", "Fiebre alta con dolor de garganta", "4.20", "34", "10 sobres", 15, 120, ("Fiebre", "Dolor de garganta", "Astenia"), ("Gripe (influenza)", "Resfriado común"), "1.55"),
        _med("med-12", "Amoxicilina 500 mg", "Antibiótico", "Tratamiento de infección bacteriana de garganta (ejemplo)", "5.80", "28", "21 cápsulas", 1, 120, ("Dolor de garganta", "Fiebre", "Odinofagia (dolor al tragar)"), ("Amigdalitis", "Faringitis"), "3.45"),
        _med("med-13", "Azitromicina 500 mg", "Antibiótico", "Alternativa antibiótica en infección bacteriana de vías altas (ejemplo)", "8.60", "16", "3 comprimidos", 12, 120, ("Dolor de garganta", "Fiebre", "Malestar general"), ("Amigdalitis", "Faringitis"), "4.10"),
        _med("med-14", "Caramelos eucalipto y miel", "Demulcente", "Alivio sintomático de garganta y tos", "2.50", "88", "1 blister", 6, 120, ("Dolor de garganta", "Tos", "Rinorrea"), ("Resfriado común", "Infección respiratoria alta (IRA alta)"), "0.60"),
        _med("med-15", "Strepsils miel y limón", "Antiséptico local", "Molestias de garganta con odinofagia", "6.80", "63", "24 pastillas", 6, 120, ("Dolor de garganta", "Odinofagia (dolor al tragar)", "Ronquera (disfonía)"), ("Faringitis", "Resfriado común"), "2.10"),
        # --- Tos (16-28) ---
        _med("med-16", "Jarabe dextrometorfano", "Antitusivo", "Tos seca", "6.20", "25", "120 ml", 6, 120, ("Tos", "Tos seca"), (), "1.80"),
        _med("med-17", "Jarabe codeína", "Antitusivo", "Tos irritativa", "8.50", "20", "120 ml", 18, 120, ("Tos", "Tos seca"), (), "3.00"),
        _med("med-18", "Jarabe ambroxol", "Mucolítico", "Tos con flema", "7.20", "35", "120 ml", 2, 120, ("Tos", "Tos con flema"), ("Bronquitis leve", "Resfriado común"), "2.20"),
        _med("med-19", "Jarabe acetilcisteína", "Mucolítico", "Flemas, tos productiva", "5.80", "40", "200 ml", 2, 120, ("Tos con flema", "Tos"), ("Bronquitis",), "1.70"),
        _med("med-20", "Pastillas tos miel", "Demulcente", "Tos leve", "4.20", "50", "20 pastillas", 6, 120, ("Tos",), ("Resfriado común",), "1.00"),
        _med("med-21", "Jarabe hiedra", "Mucolítico natural", "Tos irritativa", "6.90", "30", "100 ml", 0, 120, ("Tos", "Tos con flema"), ("Bronquitis leve",), "2.10"),
        _med("med-22", "Iniston tos", "Antitusivo", "Tos seca nocturna", "7.50", "18", "120 ml", 6, 120, ("Tos", "Tos seca"), (), "2.40"),
        _med("med-23", "Bisolvon junior", "Mucolítico", "Tos con mocos", "5.50", "25", "100 ml", 2, 12, ("Tos", "Tos con flema", "Congestión nasal"), ("Resfriado común",), "1.50"),
        _med("med-24", "Pulmo bael tos", "Fitoterapia", "Tos y garganta", "8.20", "22", "150 ml", 6, 120, ("Tos", "Dolor de garganta"), ("Resfriado común", "Faringitis leve"), "2.30"),
        _med("med-25", "Tussiflex", "Antitusivo", "Tos seca", "6.40", "30", "120 ml", 12, 120, ("Tos seca", "Tos"), (), "1.90"),
        _med("med-26", "Fluimucil 600", "Mucolítico", "Flemas espesas", "4.90", "20", "20 sobres", 14, 120, ("Tos con flema",), ("Bronquitis",), "1.40"),
        _med("med-27", "Jarabe tomillo", "Natural", "Tos y resfriado", "3.80", "45", "120 ml", 3, 120, ("Tos", "Congestión nasal"), ("Resfriado común",), "0.90"),
        _med("med-28", "Mucosan tos", "Mucolítico", "Tos productiva", "5.20", "28", "120 ml", 2, 120, ("Tos con flema", "Tos"), (), "1.30"),
        # --- Fiebre / Gripe / Resfriado (29-42) ---
        _med("med-29", "Paracetamol 1 g", "Antitérmico", "Fiebre y dolor", "4.00", "30", "20 comprimidos", 12, 120, ("Fiebre", "Dolor"), ("Gripe", "Resfriado común"), "1.50"),
        _med("med-30", "Apiretal 100 mg/ml", "Antitérmico", "Fiebre niños", "5.20", "40", "90 ml", 0, 12, ("Fiebre",), ("Gripe", "Resfriado común"), "1.80"),
        _med("med-31", "Frenadol", "Antigripal", "Gripe, fiebre, congestión", "6.50", "35", "10 sobres", 15, 120, ("Fiebre", "Congestión nasal", "Dolor"), ("Gripe", "Resfriado común"), "2.50"),
        _med("med-32", "Couldina", "Antigripal", "Síntomas gripales", "5.80", "28", "10 cápsulas", 12, 120, ("Fiebre", "Tos", "Congestión nasal"), ("Gripe",), "2.20"),
        _med("med-33", "Vitamina C 1 g", "Suplemento", "Defensas, resfriado", "7.00", "60", "20 comprimidos", 14, 120, ("Fiebre",), (), "0.90", suitable_for_pregnancy=True),
        _med("med-34", "Aspirina 500 mg", "Antitérmico", "Fiebre, dolor", "3.20", "40", "20 comprimidos", 16, 120, ("Fiebre", "Dolor", "Dolor de cabeza"), ("Gripe",), "1.10"),
        _med("med-35", "Efferalgan 500", "Paracetamol", "Fiebre y dolor leve", "4.50", "16", "16 comprimidos", 6, 120, ("Fiebre", "Dolor"), ("Resfriado común", "Gripe"), "1.60"),
        _med("med-36", "Antigripal cinfa", "Sintomático", "Gripe", "4.20", "20", "10 sobres", 18, 120, ("Fiebre", "Congestión nasal", "Tos"), ("Gripe", "Resfriado común"), "1.30"),
        _med("med-37", "Iniston gripe", "Antigripal", "Síntomas gripe", "7.20", "12", "12 cápsulas", 18, 65, ("Fiebre", "Dolor muscular", "Congestión nasal"), ("Gripe",), "2.80"),
        _med("med-38", "Propolis defensas", "Natural", "Resfriado y defensas", "12.50", "25", "30 ml", 6, 120, ("Fiebre", "Congestión nasal"), ("Resfriado común",), "3.20"),
        _med("med-39", "Paracetamol pediátrico", "Antitérmico", "Fiebre niños", "4.00", "15", "120 ml", 0, 12, ("Fiebre",), (), "1.50"),
        _med("med-40", "Echinacea complex", "Fitoterapia", "Prevención resfriado", "9.80", "30", "60 cápsulas", 12, 120, (), ("Resfriado común",), "2.40"),
        _med("med-41", "Complejo B inyectable", "Suplemento", "Cansancio, defensas", "12.00", "0", "5 ampollas", 18, 120, ("Fiebre", "Cansancio"), (), "5.00"),
        _med("med-42", "Redoxon vitamina C", "Suplemento", "Resfriado", "8.50", "45", "20 comprimidos", 12, 120, ("Fiebre", "Cansancio"), ("Resfriado común",), "2.00"),
        # --- Dolor de cabeza / Cefalea (43-54) ---
        _med("med-43", "Ibuprofeno 600 mg", "Analgésico", "Dolor de cabeza intenso", "5.20", "30", "20 comprimidos", 12, 120, ("Dolor de cabeza", "Dolor"), ("Cefalea tensional", "Migraña"), "2.20"),
        _med("med-44", "Nolotil", "Analgésico", "Dolor intenso", "6.80", "20", "20 cápsulas", 18, 120, ("Dolor de cabeza", "Dolor"), ("Cefalea", "Migraña"), "2.80"),
        _med("med-45", "Enantyum 25 mg", "Antiinflamatorio", "Dolor agudo", "4.50", "20", "20 comprimidos", 18, 120, ("Dolor de cabeza", "Dolor muscular"), ("Cefalea tensional",), "1.90"),
        _med("med-46", "Aspirina 100 mg", "Antiagregante", "Prevención cardiovascular", "2.80", "30", "30 comprimidos", 18, 120, (), (), "0.50"),
        _med("med-47", "Paracetamol 650 mg", "Analgésico", "Cefalea leve", "3.80", "24", "24 comprimidos", 6, 120, ("Dolor de cabeza",), ("Cefalea tensional",), "1.20"),
        _med("med-48", "Migraña stop", "Analgésico", "Migraña", "7.50", "12", "12 comprimidos", 18, 120, ("Dolor de cabeza",), ("Migraña",), "3.50"),
        _med("med-49", "Sumial 50 mg", "Betabloqueante", "Prevención migraña", "3.20", "28", "28 comprimidos", 18, 120, (), ("Migraña",), "0.80"),
        _med("med-50", "Dolgit", "Ibuprofeno", "Dolor y fiebre", "4.20", "40", "30 comprimidos", 12, 120, ("Dolor de cabeza", "Fiebre"), ("Cefalea tensional", "Gripe"), "1.60"),
        _med("med-51", "Cafiaspirina", "Analgésico", "Dolor de cabeza", "3.50", "20", "20 comprimidos", 16, 120, ("Dolor de cabeza",), ("Cefalea tensional",), "1.10"),
        _med("med-52", "Buscapina compositum", "Antiespasmódico", "Dolor abdominal y cefalea", "6.20", "20", "20 comprimidos", 18, 120, ("Dolor de cabeza", "Dolor abdominal"), ("Cólico",), "2.00"),
        _med("med-53", "Gelocatil 650", "Paracetamol", "Dolor leve a moderado", "4.80", "30", "30 comprimidos", 6, 120, ("Dolor de cabeza", "Dolor"), ("Cefalea tensional",), "1.40"),
        _med("med-54", "Actron 400", "Ibuprofeno", "Dolor e inflamación", "3.90", "25", "25 comprimidos", 12, 120, ("Dolor de cabeza", "Dolor muscular"), ("Cefalea",), "1.30"),
        # --- Congestión nasal / Rinitis (55-64) ---
        _med("med-55", "Frenadol descongestivo", "Descongestivo", "Congestión nasal", "6.80", "15", "10 sobres", 15, 120, ("Congestión nasal", "Mocos"), ("Resfriado común", "Rinitis"), "2.40"),
        _med("med-56", "Aspirina complex", "Analgésico descongestivo", "Resfriado con congestión", "7.20", "20", "20 comprimidos", 16, 120, ("Congestión nasal", "Fiebre", "Dolor"), ("Resfriado común",), "2.60"),
        _med("med-57", "Rino Ebastel", "Antihistamínico", "Rinitis alérgica", "8.50", "30", "30 comprimidos", 12, 120, ("Congestión nasal", "Estornudos", "Picor nasal"), ("Rinitis alérgica",), "2.90"),
        _med("med-58", "Aerius 5 mg", "Antihistamínico", "Alergia, rinitis", "6.50", "30", "30 comprimidos", 12, 120, ("Congestión nasal", "Estornudos", "Picor"), ("Rinitis alérgica", "Alergia"), "2.20"),
        _med("med-59", "Spray nasal pseudoefedrina", "Descongestivo", "Congestión nasal", "5.20", "25", "15 ml", 12, 120, ("Congestión nasal",), ("Resfriado común", "Rinitis"), "1.70"),
        _med("med-60", "María natura spray nasal", "Natural", "Congestión leve", "7.80", "20", "20 ml", 6, 120, ("Congestión nasal",), ("Resfriado común",), "2.10"),
        _med("med-61", "Bisolvon nasal", "Descongestivo", "Mocos y congestión", "4.50", "30", "15 ml", 6, 120, ("Congestión nasal", "Mocos"), ("Resfriado común",), "1.30"),
        _med("med-62", "Reactine", "Antihistamínico", "Rinitis y urticaria", "9.20", "14", "14 comprimidos", 12, 120, ("Congestión nasal", "Estornudos", "Picor"), ("Rinitis alérgica",), "3.00"),
        _med("med-63", "Clarityne", "Antihistamínico", "Alergia estacional", "5.80", "30", "30 comprimidos", 2, 120, ("Congestión nasal", "Estornudos"), ("Rinitis alérgica",), "1.80"),
        _med("med-64", "Agua de mar spray", "Higiene nasal", "Lavado nasal", "4.20", "50", "100 ml", 0, 120, ("Congestión nasal", "Mocos"), ("Resfriado común", "Rinitis"), "0.90"),
        # --- Dolor muscular / Contracturas (65-72) ---
        _med("med-65", "Dolgit gel", "Antiinflamatorio tópico", "Dolor muscular", "8.50", "35", "100 g", 12, 120, ("Dolor muscular", "Dolor"), ("Contractura muscular", "Lumbalgia"), "2.80"),
        _med("med-66", "Voltaren 1% gel", "Diclofenaco tópico", "Dolor e inflamación local", "9.20", "40", "100 g", 14, 120, ("Dolor muscular", "Dolor articular"), ("Contractura muscular", "Lumbalgia"), "3.20"),
        _med("med-67", "Flector 1%", "Ketoprofeno tópico", "Dolor muscular", "10.50", "25", "50 g", 15, 120, ("Dolor muscular",), ("Contractura muscular", "Esguince leve"), "3.50"),
        _med("med-68", "Ibuprofeno gel", "Antiinflamatorio tópico", "Dolor local", "6.80", "45", "60 g", 12, 120, ("Dolor muscular",), ("Contractura muscular",), "2.00"),
        _med("med-69", "Reflex spray", "Analgésico tópico", "Dolor muscular y articular", "7.50", "30", "100 ml", 12, 120, ("Dolor muscular", "Dolor"), ("Lumbalgia", "Contractura muscular"), "2.40"),
        _med("med-70", "Musculare 400", "Relajante muscular", "Contracturas", "5.20", "20", "20 comprimidos", 18, 120, ("Dolor muscular",), ("Contractura muscular", "Lumbalgia"), "1.90"),
        _med("med-71", "Mioflex crema", "Relajante tópico", "Tensión muscular", "8.20", "28", "50 g", 18, 120, ("Dolor muscular",), ("Contractura muscular",), "2.60"),
        _med("med-72", "Calor gel", "Rubefaciente", "Dolor muscular leve", "4.50", "40", "75 g", 12, 120, ("Dolor muscular",), (), "1.20"),
        # --- Acidez / Reflujo / Estómago (73-82) ---
        _med("med-73", "Omeprazol 20 mg", "Inhibidor bomba protones", "Acidez, reflujo", "3.50", "28", "28 cápsulas", 18, 120, ("Acidez", "Ardor de estómago"), ("Reflujo gastroesofágico",), "1.00"),
        _med("med-74", "Almax", "Antiácido", "Acidez puntual", "5.20", "24", "24 comprimidos", 12, 120, ("Acidez", "Ardor de estómago"), (), "1.80"),
        _med("med-75", "Gaviscon", "Antiácido", "Acidez y reflujo", "6.80", "24", "24 comprimidos", 12, 120, ("Acidez", "Ardor de estómago"), ("Reflujo gastroesofágico",), "2.20"),
        _med("med-76", "Ranitidina 150 mg", "Antagonista H2", "Acidez", "2.80", "20", "20 comprimidos", 12, 120, ("Acidez",), ("Reflujo",), "0.70"),
        _med("med-77", "Bicarbonato sódico", "Antiácido", "Acidez leve", "1.50", "60", "100 comprimidos", 12, 120, ("Acidez",), (), "0.30"),
        _med("med-78", "Nexium 20 mg", "IBP", "Reflujo y acidez", "8.50", "28", "28 comprimidos", 18, 120, ("Acidez", "Ardor de estómago"), ("Reflujo gastroesofágico",), "3.00"),
        _med("med-79", "Urbason 4 mg", "Corticoides", "Alergia grave", "4.20", "30", "30 comprimidos", 6, 120, (), ("Alergia",), "1.20"),
        _med("med-80", "Motilium", "Procinético", "Náuseas, digestiones lentas", "6.20", "30", "30 comprimidos", 12, 120, ("Náuseas", "Dolor abdominal"), (), "2.00"),
        _med("med-81", "Primperan", "Antiemético", "Náuseas y vómitos", "3.80", "30", "30 comprimidos", 1, 120, ("Náuseas",), (), "1.10"),
        _med("med-82", "Biodramina", "Antiemético", "Mareo y náuseas", "7.50", "10", "10 comprimidos", 2, 120, ("Náuseas", "Mareo"), (), "2.50"),
        # --- Diarrea / Estreñimiento (83-92) ---
        _med("med-83", "Fortasec", "Antidiarreico", "Diarrea aguda", "6.50", "12", "12 cápsulas", 12, 120, ("Diarrea",), ("Gastroenteritis",), "2.40"),
        _med("med-84", "Smecta", "Adsorbente", "Diarrea", "5.80", "30", "30 sobres", 0, 120, ("Diarrea", "Dolor abdominal"), ("Gastroenteritis",), "1.90"),
        _med("med-85", "Ultra levura", "Probiótico", "Diarrea y flora intestinal", "8.20", "20", "20 cápsulas", 2, 120, ("Diarrea",), ("Gastroenteritis",), "2.60"),
        _med("med-86", "Floratil", "Probiótico", "Diarrea asociada a antibióticos", "9.50", "10", "10 cápsulas", 0, 120, ("Diarrea",), (), "3.00"),
        _med("med-87", "Dulcolaxo", "Laxante", "Estreñimiento", "4.20", "20", "20 comprimidos", 12, 120, ("Estreñimiento",), (), "1.30"),
        _med("med-88", "Plantaben", "Laxante fibra", "Estreñimiento ocasional", "6.80", "30", "30 sobres", 12, 120, ("Estreñimiento",), (), "2.00"),
        _med("med-89", "Puntual", "Laxante", "Estreñimiento", "3.50", "28", "28 comprimidos", 18, 120, ("Estreñimiento",), (), "1.00"),
        _med("med-90", "Lactulosa", "Laxante osmótico", "Estreñimiento", "5.20", "20", "300 ml", 0, 120, ("Estreñimiento",), (), "1.50"),
        _med("med-91", "Enterogermina", "Probiótico", "Diarrea y equilibrio intestinal", "12.50", "20", "20 viales", 0, 120, ("Diarrea",), ("Gastroenteritis",), "3.50"),
        _med("med-92", "Carbonato activado", "Adsorbente", "Diarrea e intoxicación leve", "4.00", "40", "30 cápsulas", 12, 120, ("Diarrea",), (), "1.20"),
        # --- Alergia / Picor / Piel (93-100) ---
        _med("med-93", "Ebastel 10 mg", "Antihistamínico", "Alergia, urticaria", "5.50", "30", "30 comprimidos", 12, 120, ("Picor", "Estornudos", "Congestión nasal"), ("Rinitis alérgica", "Alergia"), "1.80"),
        _med("med-94", "Polaramine", "Antihistamínico", "Alergia y picor", "6.20", "20", "20 comprimidos", 2, 120, ("Picor", "Urticaria"), ("Alergia", "Dermatitis"), "2.00"),
        _med("med-95", "Atarax 25 mg", "Antihistamínico", "Picor y ansiedad leve", "4.80", "30", "30 comprimidos", 6, 120, ("Picor", "Ansiedad"), ("Alergia", "Dermatitis"), "1.50"),
        _med("med-96", "Cortisona crema 1%", "Corticoide tópico", "Picor e inflamación piel", "3.20", "30", "30 g", 2, 120, ("Picor", "Dermatitis"), ("Dermatitis", "Eczema"), "1.00"),
        _med("med-97", "Fenistil gel", "Antihistamínico tópico", "Picor y picaduras", "7.50", "30", "30 g", 0, 120, ("Picor",), ("Picadura", "Alergia cutánea"), "2.40"),
        _med("med-98", "After bite", "Picaduras", "Picor por picadura", "5.80", "25", "10 ml", 0, 120, ("Picor",), ("Picadura",), "1.60"),
        _med("med-99", "Caladryl", "Antipruriginoso", "Picor y quemaduras solares", "6.50", "22", "100 ml", 2, 120, ("Picor",), ("Quemadura solar", "Dermatitis"), "2.10"),
        _med("med-100", "Bepanthol crema", "Emoliente", "Piel seca e irritada", "7.20", "35", "50 g", 0, 120, ("Picor", "Piel seca"), ("Dermatitis",), "2.20"),

        # --- Respiratorio / ORL extra (101-170) ---
        _med("med-101", "Loratadina 10 mg", "Antihistamínico", "Rinitis alérgica con estornudos y picor nasal", "5.60", "40", "10 comprimidos", 12, 120, ("Estornudos", "Picor nasal", "Rinorrea"), ("Rinitis alérgica",), "1.90"),
        _med("med-102", "Cetirizina 10 mg", "Antihistamínico", "Alergia estacional con congestión y rinorrea", "5.10", "38", "20 comprimidos", 12, 120, ("Congestión nasal", "Rinorrea", "Picor"), ("Rinitis alérgica", "Alergia"), "1.70"),
        _med("med-103", "Desloratadina 5 mg", "Antihistamínico", "Rinitis alérgica persistente", "6.40", "22", "10 comprimidos", 12, 120, ("Estornudos", "Rinorrea acuosa", "Picor nasal"), ("Rinitis alérgica",), "2.10"),
        _med("med-104", "Budesonida nasal", "Corticoide nasal", "Congestión nasal por rinitis alérgica", "9.80", "18", "120 dosis", 12, 120, ("Congestión nasal", "Estornudos", "Rinorrea"), ("Rinitis alérgica",), "3.40"),
        _med("med-105", "Oximetazolina spray nasal", "Descongestivo", "Congestión nasal intensa de corta duración", "4.70", "28", "10 ml", 12, 120, ("Congestión nasal", "Presión/llenura facial", "Rinorrea"), ("Resfriado común", "Sinusitis aguda"), "1.60"),
        _med("med-106", "Xilometazolina spray nasal", "Descongestivo", "Alivio de congestión nasal", "4.40", "26", "10 ml", 12, 120, ("Congestión nasal", "Rinorrea", "Dolor facial"), ("Resfriado común", "Sinusitis aguda"), "1.50"),
        _med("med-107", "Agua de mar hipertónica", "Higiene nasal", "Lavado nasal en congestión", "5.20", "60", "100 ml", 0, 120, ("Congestión nasal", "Rinorrea", "Estornudos"), ("Resfriado común", "Rinitis alérgica"), "1.10"),
        _med("med-108", "Suero fisiológico monodosis", "Higiene nasal", "Hidratación y lavado nasal", "3.60", "80", "30 monodosis", 0, 120, ("Congestión nasal", "Rinorrea acuosa", "Sequedad ocular"), ("Resfriado común", "Rinitis alérgica"), "0.80"),
        _med("med-109", "Ambroxol 30 mg", "Mucolítico", "Tos productiva con expectoración", "6.30", "35", "20 comprimidos", 12, 120, ("Tos productiva", "Expectoración", "Opresión torácica"), ("Bronquitis aguda", "Infección respiratoria alta (IRA alta)"), "1.90"),
        _med("med-110", "Acetilcisteína 600 mg", "Mucolítico", "Flemas espesas en tos productiva", "5.20", "32", "20 sobres", 14, 120, ("Tos productiva", "Expectoración", "Opresión torácica"), ("Bronquitis aguda", "EPOC (enfermedad pulmonar obstructiva crónica)"), "1.70"),
        _med("med-111", "Guaifenesina jarabe", "Expectorante", "Tos con flema y congestión", "7.20", "18", "120 ml", 6, 120, ("Tos productiva", "Expectoración", "Congestión nasal"), ("Bronquitis aguda", "Resfriado común"), "2.40"),
        _med("med-112", "Dextrometorfano 15 mg", "Antitusivo", "Tos seca irritativa", "4.90", "24", "20 comprimidos", 12, 120, ("Tos seca", "Dolor de garganta", "Opresión torácica"), ("Infección respiratoria alta (IRA alta)", "Resfriado común"), "1.60"),
        _med("med-113", "Levodropropizina jarabe", "Antitusivo", "Tos seca nocturna", "8.40", "16", "120 ml", 2, 120, ("Tos seca", "Insomnio", "Dolor de garganta"), ("Infección respiratoria alta (IRA alta)",), "2.90"),
        _med("med-114", "Benzonatato (ejemplo)", "Antitusivo", "Tos seca con irritación", "9.10", "12", "20 cápsulas", 12, 120, ("Tos seca", "Dolor torácico", "Dolor de garganta"), ("Infección respiratoria alta (IRA alta)",), "3.10"),
        _med("med-115", "Salbutamol inhalador", "Broncodilatador", "Sibilancias y disnea episódica", "12.50", "20", "200 dosis", 6, 120, ("Sibilancias", "Disnea (falta de aire)", "Opresión torácica"), ("Asma",), "4.40"),
        _med("med-116", "Bromuro de ipratropio inhalador", "Broncodilatador", "Broncoespasmo en EPOC", "13.80", "14", "200 dosis", 18, 120, ("Disnea (falta de aire)", "Sibilancias", "Opresión torácica"), ("EPOC (enfermedad pulmonar obstructiva crónica)",), "4.80"),
        _med("med-117", "Montelukast 10 mg", "Antileucotrieno", "Control de síntomas respiratorios alérgicos", "9.90", "18", "28 comprimidos", 15, 120, ("Sibilancias", "Tos seca", "Congestión nasal"), ("Asma", "Rinitis alérgica"), "3.30"),
        _med("med-118", "Miel monodosis", "Natural", "Calma irritación de garganta", "3.20", "90", "12 monodosis", 1, 120, ("Dolor de garganta", "Tos seca", "Ronquera (disfonía)"), ("Resfriado común", "Infección respiratoria alta (IRA alta)"), "0.90"),
        _med("med-119", "Pastillas con mentol", "Demulcente", "Irritación de garganta y tos", "2.10", "120", "1 blister", 6, 120, ("Dolor de garganta", "Tos", "Ronquera (disfonía)"), ("Resfriado común", "Infección respiratoria alta (IRA alta)"), "0.55"),
        _med("med-120", "Spray nasal antihistamínico (azelastina)", "Antihistamínico", "Rinitis alérgica con estornudos", "10.90", "14", "10 ml", 12, 120, ("Estornudos", "Rinorrea", "Picor nasal"), ("Rinitis alérgica",), "3.90"),
        _med("med-121", "Paracetamol 500 mg", "Analgésico", "Dolor y fiebre en resfriado común", "3.50", "120", "20 comprimidos", 6, 120, ("Fiebre", "Dolor de cabeza", "Malestar general"), ("Resfriado común", "Gripe (influenza)"), "1.20"),
        _med("med-122", "Ibuprofeno 600 mg", "Antiinflamatorio", "Cefalea y mialgia asociadas a gripe", "5.10", "30", "20 comprimidos", 12, 120, ("Dolor de cabeza", "Dolor muscular (mialgia)", "Fiebre"), ("Gripe (influenza)",), "2.30"),
        _med("med-123", "Antigripal sobres (paracetamol + descongestivo)", "Sintomático", "Congestión nasal y fiebre con malestar", "6.90", "26", "10 sobres", 15, 120, ("Congestión nasal", "Fiebre", "Dolor de cabeza"), ("Resfriado común", "Gripe (influenza)"), "2.70"),
        _med("med-124", "Vitamina C 1 g", "Suplemento", "Soporte en síntomas catarrales (ejemplo)", "7.10", "50", "20 comprimidos", 14, 120, ("Fatiga", "Malestar general", "Dolor de garganta"), ("Infección respiratoria alta (IRA alta)", "Resfriado común"), "1.40", suitable_for_pregnancy=True),
        _med("med-125", "Pastillas para la garganta con antiséptico", "Antiséptico local", "Dolor de garganta con odinofagia", "6.40", "58", "24 pastillas", 6, 120, ("Dolor de garganta", "Odinofagia (dolor al tragar)", "Hinchazón de garganta"), ("Faringitis", "Amigdalitis"), "2.05"),
        _med("med-126", "Mupirocina nasal (ejemplo)", "Antibiótico tópico", "Colonización nasal e irritación (ejemplo)", "9.60", "10", "10 g", 12, 120, ("Congestión nasal", "Rinorrea purulenta", "Dolor facial"), ("Sinusitis aguda",), "3.80"),
        _med("med-127", "Spray nasal con corticoide", "Corticoide nasal", "Congestión nasal persistente", "11.50", "16", "120 dosis", 12, 120, ("Congestión nasal", "Rinorrea", "Estornudos"), ("Rinitis alérgica", "Sinusitis aguda"), "4.10"),
        _med("med-128", "Pastillas para la tos con miel", "Demulcente", "Tos seca y dolor de garganta", "4.20", "55", "20 pastillas", 6, 120, ("Tos seca", "Dolor de garganta", "Ronquera (disfonía)"), ("Resfriado común", "Infección respiratoria alta (IRA alta)"), "1.00"),
        _med("med-129", "Jarabe de tomillo", "Fitoterapia", "Tos productiva leve", "3.90", "42", "120 ml", 3, 120, ("Tos", "Expectoración", "Dolor de garganta"), ("Resfriado común", "Bronquitis aguda"), "0.95"),
        _med("med-130", "Pastillas de zinc (ejemplo)", "Suplemento", "Soporte en resfriado (ejemplo)", "6.60", "35", "30 pastillas", 12, 120, ("Dolor de garganta", "Rinorrea acuosa", "Fatiga"), ("Resfriado común",), "1.60"),
        _med("med-131", "Bálsamo pectoral", "Tópico", "Molestias respiratorias y congestión", "7.30", "28", "50 g", 6, 120, ("Congestión nasal", "Tos", "Opresión torácica"), ("Resfriado común", "Bronquitis aguda"), "2.20"),
        _med("med-132", "Inhalador de vapor (ejemplo)", "Dispositivo", "Congestión nasal y rinorrea", "18.90", "8", "1 unidad", 6, 120, ("Congestión nasal", "Rinorrea", "Presión/llenura facial"), ("Resfriado común", "Sinusitis aguda"), "6.50"),
        _med("med-133", "Solución para gárgaras", "Antiséptico local", "Dolor de garganta con hinchazón", "4.80", "33", "200 ml", 6, 120, ("Dolor de garganta", "Hinchazón de garganta", "Odinofagia (dolor al tragar)"), ("Faringitis", "Amigdalitis"), "1.55"),
        _med("med-134", "Pastillas para la voz", "Demulcente", "Ronquera y afonía por irritación", "5.20", "30", "20 pastillas", 6, 120, ("Ronquera (disfonía)", "Afónica/pérdida de voz", "Dolor de garganta"), ("Infección respiratoria alta (IRA alta)",), "1.70"),
        _med("med-135", "Antiséptico bucal", "Antiséptico local", "Molestias orales y de garganta", "4.10", "46", "250 ml", 6, 120, ("Úlceras bucales (aftas)", "Dolor de garganta", "Sangrado de encías"), ("Infección respiratoria alta (IRA alta)",), "1.10"),
        _med("med-136", "Solución salina ocular", "Oftálmico", "Sequedad ocular y ojos rojos (ejemplo)", "6.90", "40", "10 ml", 0, 120, ("Sequedad ocular", "Ojos rojos", "Lagrimeo"), ("Conjuntivitis", "Rinitis alérgica"), "2.10"),
        _med("med-137", "Lágrimas artificiales", "Oftálmico", "Irritación ocular", "8.20", "28", "10 ml", 0, 120, ("Sequedad ocular", "Visión borrosa", "Dolor ocular"), ("Conjuntivitis",), "2.80"),
        _med("med-138", "Colirio antihistamínico", "Oftálmico", "Picor y enrojecimiento ocular por alergia", "10.40", "16", "5 ml", 6, 120, ("Ojos rojos", "Lagrimeo", "Picor"), ("Conjuntivitis", "Rinitis alérgica"), "3.60"),
        _med("med-139", "Colirio antibiótico (ejemplo)", "Oftálmico", "Secreción ocular purulenta (ejemplo)", "11.80", "12", "5 ml", 6, 120, ("Secreción ocular", "Ojos rojos", "Dolor ocular"), ("Conjuntivitis",), "4.20"),
        _med("med-140", "Gotas óticas analgésicas", "ORL", "Dolor de oído (ejemplo)", "7.90", "20", "10 ml", 6, 120, ("Dolor de oído", "Hipoacusia (disminución de audición)", "Tinnitus (pitidos)"), ("Otitis media aguda", "Otitis externa"), "2.70"),
        _med("med-141", "Gotas óticas antibiótico (ejemplo)", "ORL", "Otitis externa con secreción (ejemplo)", "12.20", "10", "10 ml", 6, 120, ("Dolor de oído", "Otorrhea (secreción de oído)", "Hipoacusia (disminución de audición)"), ("Otitis externa",), "4.50"),
        _med("med-142", "Spray ótico (ejemplo)", "ORL", "Higiene del oído y molestias", "6.50", "25", "30 ml", 6, 120, ("Dolor de oído", "Tinnitus (pitidos)", "Aturdimiento"), ("Otitis externa",), "2.00"),
        _med("med-143", "Pastillas con anestésico local", "Anestésico local", "Dolor faríngeo intenso", "6.90", "34", "20 pastillas", 12, 120, ("Dolor de garganta", "Odinofagia (dolor al tragar)", "Dolor"), ("Faringitis",), "2.30"),
        _med("med-144", "Spray para garganta con propóleo", "Natural", "Irritación de garganta y tos", "9.40", "22", "30 ml", 6, 120, ("Dolor de garganta", "Tos", "Ronquera (disfonía)"), ("Resfriado común", "Infección respiratoria alta (IRA alta)"), "2.10"),
        _med("med-145", "Antiséptico nasal (ejemplo)", "Antiséptico", "Rinorrea purulenta y congestión", "7.80", "14", "15 ml", 12, 120, ("Rinorrea purulenta", "Congestión nasal", "Dolor facial"), ("Sinusitis aguda",), "2.90"),
        _med("med-146", "Jarabe expectorante infantil", "Expectorante", "Tos con flema en niños", "6.80", "26", "120 ml", 2, 12, ("Tos productiva", "Expectoración", "Congestión nasal"), ("Bronquitis aguda", "Resfriado común"), "2.10"),
        _med("med-147", "Mucolítico infantil", "Mucolítico", "Flemas y tos productiva", "5.60", "28", "100 ml", 2, 12, ("Tos productiva", "Expectoración", "Opresión torácica"), ("Bronquitis aguda",), "1.80"),
        _med("med-148", "Antitusivo infantil", "Antitusivo", "Tos seca nocturna", "6.20", "22", "100 ml", 2, 12, ("Tos seca", "Insomnio", "Dolor de garganta"), ("Infección respiratoria alta (IRA alta)",), "1.90"),
        _med("med-149", "Antihistamínico jarabe", "Antihistamínico", "Rinitis alérgica pediátrica", "6.40", "30", "120 ml", 2, 12, ("Estornudos", "Rinorrea acuosa", "Picor nasal"), ("Rinitis alérgica",), "2.00"),
        _med("med-150", "Spray nasal pediátrico", "Higiene nasal", "Lavado nasal en resfriado", "4.20", "55", "100 ml", 0, 12, ("Congestión nasal", "Rinorrea", "Estornudos"), ("Resfriado común",), "1.20"),
        _med("med-151", "Pastillas para chupar vitamina C", "Suplemento", "Soporte en molestias faríngeas (ejemplo)", "4.60", "70", "24 pastillas", 6, 120, ("Dolor de garganta", "Fatiga", "Malestar general"), ("Infección respiratoria alta (IRA alta)",), "1.30", suitable_for_pregnancy=True),
        _med("med-152", "Solución para nebulización salina", "Respiratorio", "Hidratación de vías respiratorias", "7.60", "24", "30 monodosis", 0, 120, ("Tos", "Opresión torácica", "Disnea de esfuerzo"), ("EPOC (enfermedad pulmonar obstructiva crónica)", "Asma"), "2.60"),
        _med("med-153", "Spray bucal antiséptico", "Antiséptico local", "Molestias de garganta y aftas", "6.10", "36", "30 ml", 6, 120, ("Dolor de garganta", "Úlceras bucales (aftas)", "Odinofagia (dolor al tragar)"), ("Faringitis",), "2.20"),
        _med("med-154", "Pastillas para gargantas con sal", "Demulcente", "Irritación faríngea", "2.30", "110", "20 pastillas", 6, 120, ("Dolor de garganta", "Odinofagia (dolor al tragar)", "Hinchazón de garganta"), ("Infección respiratoria alta (IRA alta)", "Resfriado común"), "0.60"),
        _med("med-155", "Spray nasal con aceites (ejemplo)", "Natural", "Sequedad e irritación nasal", "8.10", "18", "20 ml", 6, 120, ("Sequedad ocular", "Congestión nasal", "Rinorrea"), ("Rinitis alérgica",), "2.50"),
        _med("med-156", "Antigripal cápsulas", "Sintomático", "Gripe con tos y congestión", "6.30", "22", "12 cápsulas", 18, 120, ("Fiebre", "Tos", "Congestión nasal"), ("Gripe (influenza)",), "2.10"),
        _med("med-157", "Descongestivo oral (pseudoefedrina)", "Descongestivo", "Congestión nasal en resfriado", "5.90", "18", "20 comprimidos", 15, 120, ("Congestión nasal", "Rinorrea", "Presión/llenura facial"), ("Resfriado común", "Sinusitis aguda"), "2.20"),
        _med("med-158", "Antihistamínico + descongestivo", "Antialérgico", "Rinitis alérgica con congestión", "9.40", "14", "20 comprimidos", 15, 120, ("Congestión nasal", "Estornudos", "Rinorrea acuosa"), ("Rinitis alérgica",), "3.40"),
        _med("med-159", "Spray nasal isotónico", "Higiene nasal", "Lavado nasal diario", "4.10", "75", "100 ml", 0, 120, ("Congestión nasal", "Rinorrea", "Picor nasal"), ("Rinitis alérgica", "Resfriado común"), "1.05"),
        _med("med-160", "Pastillas expectorantes", "Expectorante", "Tos con flema", "4.80", "40", "20 pastillas", 12, 120, ("Tos productiva", "Expectoración", "Opresión torácica"), ("Bronquitis aguda",), "1.40"),
        _med("med-161", "Gárgaras antiinflamatorias", "Antiinflamatorio local", "Dolor de garganta con hinchazón", "6.20", "20", "200 ml", 12, 120, ("Dolor de garganta", "Hinchazón de garganta", "Odinofagia (dolor al tragar)"), ("Faringitis", "Amigdalitis"), "2.10"),
        _med("med-162", "Nebulizador (ejemplo)", "Dispositivo", "Apoyo en disnea episódica", "39.90", "6", "1 unidad", 0, 120, ("Disnea (falta de aire)", "Sibilancias", "Opresión torácica"), ("Asma", "EPOC (enfermedad pulmonar obstructiva crónica)"), "12.00"),
        _med("med-163", "Termómetro digital", "Dispositivo", "Control de fiebre", "6.50", "40", "1 unidad", 0, 120, ("Fiebre", "Febrícula", "Escalofríos"), ("Gripe (influenza)", "COVID-19", "Resfriado común"), "2.60"),
        _med("med-164", "Mascarillas (pack)", "Dispositivo", "Prevención en infecciones respiratorias (ejemplo)", "4.90", "120", "10 unidades", 0, 120, ("Tos", "Fiebre", "Rinorrea"), ("COVID-19", "Gripe (influenza)"), "1.10"),
        _med("med-165", "Solución de lavado ocular", "Oftálmico", "Limpieza ocular en secreción", "5.20", "35", "100 ml", 0, 120, ("Secreción ocular", "Ojos rojos", "Lagrimeo"), ("Conjuntivitis",), "1.60"),
        _med("med-166", "Caramelos balsámicos", "Demulcente", "Tos y dolor de garganta", "2.40", "90", "1 blister", 6, 120, ("Tos", "Dolor de garganta", "Ronquera (disfonía)"), ("Resfriado común",), "0.70"),
        _med("med-167", "Spray bucal hidratante", "ORL", "Afonía y sequedad", "8.90", "18", "30 ml", 12, 120, ("Afónica/pérdida de voz", "Boca seca (xerostomía)", "Dolor de garganta"), ("Infección respiratoria alta (IRA alta)",), "2.80"),
        _med("med-168", "Pastillas para afonía", "Demulcente", "Ronquera y afonía", "5.80", "26", "20 pastillas", 6, 120, ("Afónica/pérdida de voz", "Ronquera (disfonía)", "Dolor de garganta"), ("Infección respiratoria alta (IRA alta)",), "1.90"),
        _med("med-169", "Eucaliptol inhalación (ejemplo)", "Natural", "Congestión nasal y tos", "6.90", "14", "50 ml", 12, 120, ("Congestión nasal", "Tos", "Presión/llenura facial"), ("Resfriado común", "Sinusitis aguda"), "2.00"),
        _med("med-170", "Spray nasal emoliente", "Higiene nasal", "Irritación nasal", "7.20", "20", "20 ml", 6, 120, ("Epistaxis (sangrado nasal)", "Congestión nasal", "Rinorrea"), ("Rinitis alérgica",), "2.30"),

        # --- Digestivo extra (171-230) ---
        _med("med-171", "Omeprazol 20 mg (genérico)", "Inhibidor bomba protones", "Ardor de estómago y reflujo", "3.20", "40", "28 cápsulas", 18, 120, ("Pirosis", "Reflujo/regurgitación", "Dolor epigástrico"), ("Reflujo gastroesofágico (ERGE)", "Gastritis"), "1.10"),
        _med("med-172", "Pantoprazol 40 mg", "IBP", "Reflujo con dolor epigástrico", "5.60", "24", "28 comprimidos", 18, 120, ("Pirosis", "Dolor epigástrico", "Náuseas"), ("Reflujo gastroesofágico (ERGE)", "Úlcera péptica"), "2.10"),
        _med("med-173", "Algeldrato + magaldrato", "Antiácido", "Acidez y ardor de estómago", "4.90", "30", "24 sobres", 12, 120, ("Acidez/ardor", "Pirosis", "Reflujo/regurgitación"), ("Gastritis", "Reflujo gastroesofágico (ERGE)"), "1.80"),
        _med("med-174", "Sucralfato (ejemplo)", "Gastroprotector", "Dolor epigástrico y úlcera (ejemplo)", "7.90", "16", "60 sobres", 18, 120, ("Dolor epigástrico", "Náuseas", "Pérdida de apetito (anorexia)"), ("Úlcera péptica", "Gastritis"), "2.90"),
        _med("med-175", "Simeticona", "Antiflatulento", "Gases y distensión abdominal", "3.80", "55", "40 cápsulas", 0, 120, ("Flatulencia", "Distensión abdominal", "Dolor abdominal"), ("Síndrome del intestino irritable (SII)",), "1.20"),
        _med("med-176", "Butilhioscina", "Antiespasmódico", "Cólicos y dolor abdominal", "6.10", "30", "20 comprimidos", 12, 120, ("Dolor abdominal", "Distensión abdominal", "Náuseas"), ("Síndrome del intestino irritable (SII)", "Gastroenteritis aguda"), "2.10"),
        _med("med-177", "Loperamida", "Antidiarreico", "Diarrea aguda sin fiebre", "6.20", "18", "12 cápsulas", 12, 120, ("Diarrea", "Tenesmo (sensación de evacuación incompleta)", "Dolor abdominal"), ("Diarrea aguda", "Gastroenteritis aguda"), "2.30"),
        _med("med-178", "Racecadotrilo", "Antidiarreico", "Diarrea aguda", "7.40", "14", "10 cápsulas", 12, 120, ("Diarrea acuosa", "Dolor abdominal", "Malestar general"), ("Diarrea aguda", "Gastroenteritis aguda"), "2.80"),
        _med("med-179", "Sales de rehidratación oral", "Rehidratación", "Reposición en diarrea y vómitos", "4.20", "60", "6 sobres", 0, 120, ("Diarrea", "Vómitos", "Debilidad"), ("Gastroenteritis aguda", "Diarrea aguda"), "1.30", suitable_for_pregnancy=True),
        _med("med-180", "Metoclopramida (ejemplo)", "Antiemético", "Náuseas y vómitos", "3.50", "22", "20 comprimidos", 12, 120, ("Náuseas", "Vómitos", "Dolor abdominal"), ("Gastroenteritis aguda",), "1.20"),
        _med("med-181", "Ondansetrón (ejemplo)", "Antiemético", "Vómitos persistentes (ejemplo)", "9.90", "10", "10 comprimidos", 12, 120, ("Vómitos", "Náuseas", "Malestar general"), ("Gastroenteritis aguda",), "3.90"),
        _med("med-182", "Jengibre cápsulas", "Natural", "Náuseas leves", "6.80", "30", "30 cápsulas", 12, 120, ("Náuseas", "Mareo", "Pérdida de apetito (anorexia)"), ("Gastritis",), "2.10", suitable_for_pregnancy=True),
        _med("med-183", "Probiótico 10 cepas", "Probiótico", "Diarrea asociada a gastroenteritis", "11.90", "25", "20 cápsulas", 2, 120, ("Diarrea", "Dolor abdominal", "Malestar general"), ("Gastroenteritis aguda",), "4.10", suitable_for_pregnancy=True),
        _med("med-184", "Saccharomyces boulardii", "Probiótico", "Diarrea asociada a antibióticos (ejemplo)", "9.20", "20", "10 cápsulas", 2, 120, ("Diarrea", "Dolor abdominal", "Fatiga"), ("Gastroenteritis aguda",), "3.20", suitable_for_pregnancy=True),
        _med("med-185", "Fibra soluble sobres", "Laxante fibra", "Estreñimiento funcional", "7.10", "22", "30 sobres", 12, 120, ("Estreñimiento", "Distensión abdominal", "Dolor abdominal"), ("Estreñimiento funcional", "Síndrome del intestino irritable (SII)"), "2.40", suitable_for_pregnancy=True),
        _med("med-186", "Macrogol sobres", "Laxante osmótico", "Estreñimiento", "8.20", "18", "20 sobres", 12, 120, ("Estreñimiento", "Dolor abdominal", "Tenesmo (sensación de evacuación incompleta)"), ("Estreñimiento funcional",), "2.90", suitable_for_pregnancy=True),
        _med("med-187", "Senósidos", "Laxante estimulante", "Estreñimiento ocasional", "4.60", "30", "20 comprimidos", 18, 120, ("Estreñimiento", "Distensión abdominal", "Dolor abdominal"), ("Estreñimiento funcional",), "1.60"),
        _med("med-188", "Enema (ejemplo)", "Laxante", "Estreñimiento agudo (ejemplo)", "6.90", "12", "1 unidad", 18, 120, ("Estreñimiento", "Dolor rectal", "Tenesmo (sensación de evacuación incompleta)"), ("Estreñimiento funcional",), "2.30"),
        _med("med-189", "Crema hemorroidal", "Tópico", "Picor anal y dolor rectal", "7.50", "28", "30 g", 18, 120, ("Prurito anal", "Dolor rectal", "Sangrado rectal"), ("Hemorroides", "Fisura anal"), "2.70"),
        _med("med-190", "Supositorios hemorroidales", "Tópico", "Dolor y sangrado rectal por hemorroides", "8.10", "20", "12 supositorios", 18, 120, ("Dolor rectal", "Sangrado rectal", "Prurito anal"), ("Hemorroides",), "2.90"),
        _med("med-191", "Pomada para fisura anal", "Tópico", "Dolor y sangrado al defecar", "9.80", "14", "30 g", 18, 120, ("Dolor rectal", "Sangrado rectal", "Tenesmo (sensación de evacuación incompleta)"), ("Fisura anal",), "3.40"),
        _med("med-192", "Carbón activado", "Adsorbente", "Diarrea e intoxicación leve", "4.10", "45", "30 cápsulas", 12, 120, ("Diarrea", "Flatulencia", "Dolor abdominal"), ("Diarrea aguda",), "1.25"),
        _med("med-193", "Bismuto (ejemplo)", "Antidiarreico", "Diarrea con molestias digestivas", "7.60", "18", "20 comprimidos", 12, 120, ("Diarrea", "Náuseas", "Dolor abdominal"), ("Gastroenteritis aguda",), "2.70"),
        _med("med-194", "Antiespasmódico gotas", "Antiespasmódico", "Cólico abdominal", "5.90", "20", "30 ml", 1, 120, ("Dolor abdominal", "Distensión abdominal", "Náuseas"), ("Síndrome del intestino irritable (SII)",), "2.10"),
        _med("med-195", "Digestivo enzimas (ejemplo)", "Digestivo", "Digestión pesada con náuseas", "9.20", "18", "30 comprimidos", 12, 120, ("Náuseas", "Eructos", "Distensión abdominal"), ("Gastritis",), "3.10"),
        _med("med-196", "Antiemético mareo", "Antiemético", "Mareo con náuseas", "7.50", "16", "10 comprimidos", 2, 120, ("Mareo", "Náuseas", "Vómitos"), ("Gastroenteritis aguda",), "2.50"),
        _med("med-197", "Antiácido masticable", "Antiácido", "Acidez puntual", "4.60", "44", "24 comprimidos", 12, 120, ("Acidez/ardor", "Pirosis", "Reflujo/regurgitación"), ("Reflujo gastroesofágico (ERGE)",), "1.60"),
        _med("med-198", "Gaviscon (genérico)", "Antiácido", "Reflujo con regurgitación", "6.50", "35", "24 sobres", 12, 120, ("Reflujo/regurgitación", "Pirosis", "Dolor epigástrico"), ("Reflujo gastroesofágico (ERGE)",), "2.10", suitable_for_pregnancy=True),
        _med("med-199", "Antiemético chicles (jengibre)", "Natural", "Náuseas leves y mareo", "3.90", "60", "20 chicles", 12, 120, ("Náuseas", "Mareo", "Malestar general"), ("Gastritis",), "1.10", suitable_for_pregnancy=True),
        _med("med-200", "Protector gástrico (alginato)", "Gastroprotector", "Pirosis y reflujo", "7.20", "28", "20 sobres", 12, 120, ("Pirosis", "Reflujo/regurgitación", "Dolor epigástrico"), ("Reflujo gastroesofágico (ERGE)",), "2.60", suitable_for_pregnancy=True),
        _med("med-201", "Té digestivo", "Natural", "Distensión y gases", "3.10", "70", "20 bolsitas", 12, 120, ("Flatulencia", "Distensión abdominal", "Eructos"), ("Síndrome del intestino irritable (SII)",), "0.90", suitable_for_pregnancy=True),
        _med("med-202", "Antidiarreico infantil (racecadotrilo)", "Antidiarreico", "Diarrea acuosa en niños", "8.20", "16", "10 sobres", 0, 12, ("Diarrea acuosa", "Dolor abdominal", "Debilidad"), ("Diarrea aguda", "Gastroenteritis aguda"), "2.90"),
        _med("med-203", "Rehidratación oral infantil", "Rehidratación", "Diarrea y vómitos pediátricos", "4.40", "50", "6 sobres", 0, 12, ("Diarrea", "Vómitos", "Debilidad"), ("Gastroenteritis aguda",), "1.40"),
        _med("med-204", "Probiótico infantil", "Probiótico", "Recuperación de flora tras diarrea", "10.50", "20", "10 sobres", 0, 12, ("Diarrea", "Dolor abdominal", "Malestar general"), ("Gastroenteritis aguda",), "3.90"),
        _med("med-205", "Laxante infantil (lactulosa)", "Laxante osmótico", "Estreñimiento pediátrico", "5.10", "18", "300 ml", 0, 12, ("Estreñimiento", "Dolor abdominal", "Distensión abdominal"), ("Estreñimiento funcional",), "1.60"),
        _med("med-206", "Antiespasmódico infantil", "Antiespasmódico", "Dolor abdominal tipo cólico", "6.20", "16", "30 ml", 1, 12, ("Dolor abdominal", "Distensión abdominal", "Náuseas"), ("Síndrome del intestino irritable (SII)",), "2.10"),
        _med("med-207", "Antiácido líquido", "Antiácido", "Acidez", "5.40", "25", "250 ml", 12, 120, ("Acidez/ardor", "Pirosis", "Reflujo/regurgitación"), ("Gastritis", "Reflujo gastroesofágico (ERGE)"), "1.90"),
        _med("med-208", "Lactasa (ejemplo)", "Digestivo", "Distensión y diarrea tras lácteos (ejemplo)", "12.20", "14", "30 comprimidos", 12, 120, ("Distensión abdominal", "Diarrea", "Dolor abdominal"), ("Síndrome del intestino irritable (SII)",), "4.20"),
        _med("med-209", "Antiemético en gotas", "Antiemético", "Náuseas leves", "4.90", "30", "30 ml", 1, 120, ("Náuseas", "Vómitos", "Malestar general"), ("Gastroenteritis aguda",), "1.70"),
        _med("med-210", "Protector hepático (ejemplo)", "Suplemento", "Fatiga y malestar (ejemplo)", "14.90", "10", "30 cápsulas", 18, 120, ("Fatiga", "Malestar general", "Pérdida de apetito (anorexia)"), ("Hígado graso no alcohólico (EHGNA/NAFLD)",), "5.20"),
        _med("med-211", "Antiespasmódico colon irritable", "Antiespasmódico", "Dolor abdominal recurrente", "7.80", "18", "30 comprimidos", 18, 120, ("Dolor abdominal", "Distensión abdominal", "Tenesmo (sensación de evacuación incompleta)"), ("Síndrome del intestino irritable (SII)",), "2.80"),
        _med("med-212", "Antidiarreico adsorbente", "Adsorbente", "Diarrea y gases", "5.90", "30", "30 sobres", 0, 120, ("Diarrea", "Flatulencia", "Dolor abdominal"), ("Gastroenteritis aguda",), "2.00"),
        _med("med-213", "Antiflatulento gotas", "Antiflatulento", "Gases y cólicos", "4.20", "40", "30 ml", 0, 120, ("Flatulencia", "Dolor abdominal", "Distensión abdominal"), ("Síndrome del intestino irritable (SII)",), "1.40", suitable_for_pregnancy=True),
        _med("med-214", "Antihemorroidal toallitas", "Tópico", "Higiene y picor anal", "5.10", "40", "20 toallitas", 18, 120, ("Prurito anal", "Dolor rectal", "Sangrado rectal"), ("Hemorroides",), "1.60"),
        _med("med-215", "Laxante supositorios glicerina", "Laxante", "Estreñimiento", "3.90", "30", "12 supositorios", 0, 120, ("Estreñimiento", "Dolor rectal", "Tenesmo (sensación de evacuación incompleta)"), ("Estreñimiento funcional",), "1.20", suitable_for_pregnancy=True),
        _med("med-216", "Psyllium", "Laxante fibra", "Estreñimiento funcional y SII", "6.70", "28", "30 sobres", 12, 120, ("Estreñimiento", "Distensión abdominal", "Dolor abdominal"), ("Estreñimiento funcional", "Síndrome del intestino irritable (SII)"), "2.10", suitable_for_pregnancy=True),
        _med("med-217", "Antiemético parche (ejemplo)", "Antiemético", "Mareo y náuseas", "12.80", "8", "4 parches", 18, 120, ("Mareo", "Náuseas", "Vómitos"), ("Gastroenteritis aguda",), "4.50"),
        _med("med-218", "Enzimas digestivas", "Digestivo", "Digestiones pesadas", "8.60", "20", "30 cápsulas", 12, 120, ("Eructos", "Distensión abdominal", "Náuseas"), ("Gastritis",), "2.90"),
        _med("med-219", "Antirreflujo infantil (alginato)", "Gastroprotector", "Regurgitación y pirosis (ejemplo)", "7.90", "14", "150 ml", 0, 12, ("Reflujo/regurgitación", "Pirosis", "Malestar general"), ("Reflujo gastroesofágico (ERGE)",), "2.70"),
        _med("med-220", "Antiácido efervescente", "Antiácido", "Acidez", "3.20", "55", "10 sobres", 12, 120, ("Acidez/ardor", "Pirosis", "Dolor epigástrico"), ("Gastritis",), "1.10"),
        _med("med-221", "Antidiarreico probiótico", "Probiótico", "Diarrea y flora", "9.40", "20", "10 cápsulas", 12, 120, ("Diarrea", "Dolor abdominal", "Fatiga"), ("Gastroenteritis aguda",), "3.20", suitable_for_pregnancy=True),
        _med("med-222", "Sales biliares (ejemplo)", "Digestivo", "Digestión pesada (ejemplo)", "10.90", "10", "30 comprimidos", 18, 120, ("Dolor en hipocondrio derecho", "Náuseas", "Pérdida de apetito (anorexia)"), ("Colelitiasis (cálculos biliares)",), "3.90"),
        _med("med-223", "Antiespasmódico biliar (ejemplo)", "Antiespasmódico", "Dolor en hipocondrio derecho", "8.20", "12", "20 comprimidos", 18, 120, ("Dolor en hipocondrio derecho", "Náuseas", "Dolor abdominal"), ("Colelitiasis (cálculos biliares)", "Colecistitis"), "2.90"),
        _med("med-224", "Antiácido con alginato", "Antiácido", "Reflujo gastroesofágico", "7.10", "26", "24 comprimidos", 12, 120, ("Reflujo/regurgitación", "Pirosis", "Dolor epigástrico"), ("Reflujo gastroesofágico (ERGE)",), "2.60", suitable_for_pregnancy=True),
        _med("med-225", "Laxante microenema", "Laxante", "Estreñimiento", "6.20", "20", "1 unidad", 18, 120, ("Estreñimiento", "Dolor rectal", "Tenesmo (sensación de evacuación incompleta)"), ("Estreñimiento funcional",), "2.10"),
        _med("med-226", "Antiulceroso (ejemplo)", "Gastroprotector", "Dolor epigástrico", "9.50", "12", "28 comprimidos", 18, 120, ("Dolor epigástrico", "Náuseas", "Pérdida de apetito (anorexia)"), ("Úlcera péptica",), "3.40"),
        _med("med-227", "Antidiarreico de viaje (ejemplo)", "Antidiarreico", "Diarrea aguda del viajero (ejemplo)", "8.90", "14", "12 cápsulas", 18, 120, ("Diarrea", "Dolor abdominal", "Malestar general"), ("Diarrea aguda",), "3.20"),
        _med("med-228", "Infusión antináusea", "Natural", "Náuseas y malestar", "2.90", "80", "20 bolsitas", 12, 120, ("Náuseas", "Malestar general", "Pérdida de apetito (anorexia)"), ("Gastritis",), "0.85", suitable_for_pregnancy=True),
        _med("med-229", "Antiácido en sobres", "Antiácido", "Acidez", "4.90", "30", "24 sobres", 12, 120, ("Acidez/ardor", "Pirosis", "Reflujo/regurgitación"), ("Gastritis",), "1.70"),
        _med("med-230", "Protector gástrico infantil (ejemplo)", "Gastroprotector", "Pirosis y dolor epigástrico (ejemplo)", "6.60", "16", "150 ml", 0, 12, ("Pirosis", "Dolor epigástrico", "Náuseas"), ("Gastritis",), "2.10"),

        # --- Dolor / Neurología / Musculoesquelético extra (231-280) ---
        _med("med-231", "Paracetamol 500 mg (genérico)", "Analgésico", "Cefalea leve", "3.10", "120", "20 comprimidos", 6, 120, ("Dolor de cabeza", "Malestar general", "Fatiga"), ("Cefalea tensional",), "1.10"),
        _med("med-232", "Naproxeno 250 mg", "Antiinflamatorio", "Cefalea y dolor muscular", "4.20", "40", "30 comprimidos", 16, 120, ("Dolor de cabeza", "Dolor muscular (mialgia)", "Dolor"), ("Cefalea tensional", "Migraña"), "2.00"),
        _med("med-233", "Ibuprofeno 400 mg (genérico)", "Antiinflamatorio", "Dolor muscular y fiebre", "3.90", "80", "20 comprimidos", 12, 120, ("Dolor muscular (mialgia)", "Fiebre", "Dolor"), ("Gripe (influenza)",), "1.90"),
        _med("med-234", "Metamizol (ejemplo)", "Analgésico", "Dolor intenso", "6.80", "22", "20 cápsulas", 18, 120, ("Dolor", "Dolor localizado con presión", "Sudor frío"), ("Lumbalgia mecánica", "Cervicalgia"), "2.80"),
        _med("med-235", "Diclofenaco gel", "Antiinflamatorio tópico", "Dolor articular localizado", "8.50", "30", "100 g", 14, 120, ("Dolor articular (artralgia)", "Inflamación articular", "Limitación de movilidad"), ("Osteoartrosis (artrosis)",), "2.90"),
        _med("med-236", "Ibuprofeno gel", "Antiinflamatorio tópico", "Dolor muscular localizado", "6.80", "45", "60 g", 12, 120, ("Dolor muscular (mialgia)", "Dolor localizado con presión", "Limitación de movilidad"), ("Tendinitis (p. ej., manguito rotador)",), "2.00"),
        _med("med-237", "Parche térmico", "Dispositivo", "Lumbalgia mecánica", "6.90", "40", "2 parches", 12, 120, ("Dolor lumbar", "Dolor de espalda", "Rigidez articular"), ("Lumbalgia mecánica",), "2.40"),
        _med("med-238", "Crema calor", "Tópico", "Contractura y dolor muscular", "4.60", "55", "75 g", 12, 120, ("Dolor muscular (mialgia)", "Calambres", "Dolor localizado con presión"), ("Fibromialgia", "Cervicalgia"), "1.40"),
        _med("med-239", "Relajante muscular (ejemplo)", "Relajante muscular", "Contractura y lumbalgia", "7.80", "18", "20 comprimidos", 18, 120, ("Dolor lumbar", "Calambres", "Limitación de movilidad"), ("Lumbalgia mecánica", "Cervicalgia"), "2.90"),
        _med("med-240", "Magnesio", "Suplemento", "Calambres y fatiga", "9.50", "28", "30 comprimidos", 12, 120, ("Calambres", "Fatiga", "Debilidad"), ("Fibromialgia",), "3.10", suitable_for_pregnancy=True),
        _med("med-241", "Triptán (ejemplo)", "Antimigrañoso", "Crisis de migraña", "12.90", "12", "6 comprimidos", 18, 120, ("Migraña (dolor pulsátil)", "Fotofobia", "Náuseas"), ("Migraña",), "4.80"),
        _med("med-242", "Antiemético para migraña (ejemplo)", "Antiemético", "Migraña con náuseas", "8.90", "14", "10 comprimidos", 18, 120, ("Migraña (dolor pulsátil)", "Náuseas", "Vómitos"), ("Migraña",), "3.20"),
        _med("med-243", "Analgésico combinado (ejemplo)", "Analgésico", "Cefalea tensional", "6.20", "20", "20 comprimidos", 16, 120, ("Dolor de cabeza", "Fonofobia", "Irritabilidad"), ("Cefalea tensional",), "2.20"),
        _med("med-244", "Antivertiginoso (ejemplo)", "Neurología", "Vértigo y náuseas", "9.40", "14", "20 comprimidos", 12, 120, ("Vértigo", "Náuseas", "Aturdimiento"), ("Vértigo periférico (VPPB)",), "3.30"),
        _med("med-245", "Collarín cervical", "Dispositivo", "Cervicalgia", "14.90", "10", "1 unidad", 12, 120, ("Dolor cervical", "Rigidez articular", "Limitación de movilidad"), ("Cervicalgia",), "5.50"),
        _med("med-246", "Tobillera elástica", "Dispositivo", "Esguince leve", "12.50", "14", "1 unidad", 12, 120, ("Dolor de pie", "Edema (hinchazón)", "Limitación de movilidad"), ("Esguince de tobillo",), "4.90"),
        _med("med-247", "Rodillera", "Dispositivo", "Dolor de rodilla por artrosis", "16.90", "10", "1 unidad", 12, 120, ("Dolor de rodilla", "Rigidez articular", "Limitación de movilidad"), ("Osteoartrosis (artrosis)",), "6.40"),
        _med("med-248", "Bastón", "Dispositivo", "Apoyo en dolor de cadera", "19.90", "8", "1 unidad", 18, 120, ("Dolor de cadera", "Limitación de movilidad", "Dolor de espalda"), ("Osteoporosis", "Osteoartrosis (artrosis)"), "7.10"),
        _med("med-249", "Calcio + vitamina D", "Suplemento", "Soporte óseo", "9.90", "25", "60 comprimidos", 18, 120, ("Dolor articular (artralgia)", "Debilidad", "Fatiga"), ("Osteoporosis",), "3.20"),
        _med("med-250", "Ácido úrico (alopurinol ejemplo)", "Metabólico", "Prevención de gota (ejemplo)", "5.80", "20", "30 comprimidos", 18, 120, ("Dolor articular (artralgia)", "Inflamación articular", "Dolor localizado con presión"), ("Gota",), "2.10"),
        _med("med-251", "Colchicina (ejemplo)", "Antiinflamatorio", "Crisis de gota (ejemplo)", "6.40", "14", "20 comprimidos", 18, 120, ("Dolor articular (artralgia)", "Inflamación articular", "Dolor"), ("Gota",), "2.30"),
        _med("med-252", "Crema antiinflamatoria", "Tópico", "Dolor de muñeca", "7.20", "26", "60 g", 12, 120, ("Dolor de muñeca", "Inflamación articular", "Limitación de movilidad"), ("Tendinitis (p. ej., manguito rotador)",), "2.40"),
        _med("med-253", "Pomada para contracturas", "Tópico", "Dolor de espalda y contractura", "6.20", "30", "75 g", 12, 120, ("Dolor de espalda", "Dolor localizado con presión", "Rigidez articular"), ("Lumbalgia mecánica",), "2.10"),
        _med("med-254", "Antineurálgico (gabapentina ejemplo)", "Neurología", "Dolor neuropático (ejemplo)", "9.60", "12", "30 cápsulas", 18, 120, ("Hormigueo (parestesias)", "Entumecimiento", "Dolor"), ("Neuropatía periférica",), "3.50"),
        _med("med-255", "Complejo B", "Suplemento", "Soporte neurológico (ejemplo)", "7.90", "18", "30 comprimidos", 12, 120, ("Hormigueo (parestesias)", "Fatiga", "Debilidad"), ("Déficit de vitamina B12",), "2.60"),
        _med("med-256", "Vitamina B12", "Suplemento", "Déficit de B12 (ejemplo)", "8.50", "16", "30 comprimidos", 12, 120, ("Fatiga", "Debilidad", "Pérdida de memoria"), ("Déficit de vitamina B12", "Anemia ferropénica"), "2.90", suitable_for_pregnancy=True),
        _med("med-257", "Hierro oral", "Suplemento", "Anemia ferropénica (ejemplo)", "6.40", "20", "30 comprimidos", 12, 120, ("Fatiga", "Palidez", "Debilidad"), ("Anemia ferropénica",), "2.20", suitable_for_pregnancy=True),
        _med("med-258", "Ácido fólico", "Suplemento", "Déficit de folato (ejemplo)", "4.80", "30", "30 comprimidos", 12, 120, ("Fatiga", "Palidez", "Debilidad"), ("Déficit de folato",), "1.60", suitable_for_pregnancy=True),
        _med("med-259", "Antifibróticos (ejemplo)", "Reumatología", "Dolor generalizado (ejemplo)", "11.20", "8", "30 cápsulas", 18, 120, ("Dolor generalizado", "Fatiga", "Insomnio"), ("Fibromialgia",), "4.00"),
        _med("med-260", "Gel frío", "Tópico", "Dolor articular y edema", "5.50", "35", "100 g", 12, 120, ("Edema (hinchazón)", "Dolor articular (artralgia)", "Dolor localizado con presión"), ("Esguince de tobillo", "Osteoartrosis (artrosis)"), "1.80"),
        _med("med-261", "Antiinflamatorio oral (diclofenaco)", "Antiinflamatorio", "Dolor articular", "6.90", "20", "20 comprimidos", 18, 120, ("Dolor articular (artralgia)", "Inflamación articular", "Rigidez articular"), ("Osteoartrosis (artrosis)", "Artritis reumatoide"), "2.60"),
        _med("med-262", "Corticoide oral (ejemplo)", "Corticoides", "Brote inflamatorio (ejemplo)", "5.20", "14", "30 comprimidos", 18, 120, ("Inflamación articular", "Dolor articular (artralgia)", "Rigidez articular"), ("Artritis reumatoide",), "2.10"),
        _med("med-263", "Muleta", "Dispositivo", "Apoyo en esguince", "14.50", "10", "1 unidad", 12, 120, ("Dolor de pie", "Limitación de movilidad", "Edema (hinchazón)"), ("Esguince de tobillo",), "5.20"),
        _med("med-264", "Vendas elásticas", "Dispositivo", "Compresión en edema", "3.90", "60", "1 unidad", 12, 120, ("Edema (hinchazón)", "Dolor localizado con presión", "Limitación de movilidad"), ("Esguince de tobillo",), "1.20"),
        _med("med-265", "Antiespasmódico dolor lumbar (ejemplo)", "Relajante muscular", "Lumbalgia con calambres", "7.20", "16", "20 comprimidos", 18, 120, ("Dolor lumbar", "Calambres", "Rigidez articular"), ("Lumbalgia mecánica",), "2.70"),
        _med("med-266", "Analgésico tópico spray", "Tópico", "Dolor muscular", "7.30", "28", "100 ml", 12, 120, ("Dolor muscular (mialgia)", "Dolor localizado con presión", "Limitación de movilidad"), ("Cervicalgia",), "2.30"),
        _med("med-267", "Cojín lumbar", "Dispositivo", "Apoyo en lumbalgia", "24.90", "8", "1 unidad", 18, 120, ("Dolor lumbar", "Dolor de espalda", "Rigidez articular"), ("Lumbalgia mecánica",), "8.40"),
        _med("med-268", "Gel para articulaciones", "Tópico", "Dolor articular", "8.10", "20", "100 g", 12, 120, ("Dolor articular (artralgia)", "Rigidez articular", "Limitación de movilidad"), ("Osteoartrosis (artrosis)",), "2.70"),
        _med("med-269", "Antimigrañoso preventivo (ejemplo)", "Neurología", "Prevención de migraña (ejemplo)", "10.40", "12", "28 comprimidos", 18, 120, ("Migraña (dolor pulsátil)", "Fotofobia", "Náuseas"), ("Migraña",), "3.80"),
        _med("med-270", "Spray frío deportivo", "Tópico", "Dolor y edema en esguince", "6.80", "25", "200 ml", 12, 120, ("Edema (hinchazón)", "Dolor localizado con presión", "Limitación de movilidad"), ("Esguince de tobillo",), "2.20"),
        _med("med-271", "Analgésico dental (ibuprofeno)", "Analgésico", "Dolor dental", "4.20", "40", "20 comprimidos", 12, 120, ("Dolor dental", "Dolor localizado con presión", "Sangrado de encías"), ("Infección respiratoria alta (IRA alta)",), "1.60"),
        _med("med-272", "Gel dental anestésico", "Tópico", "Dolor dental localizado", "6.90", "22", "10 g", 6, 120, ("Dolor dental", "Sensibilidad dental", "Dolor al masticar"), ("Infección respiratoria alta (IRA alta)",), "2.40"),
        _med("med-273", "Enjuague bucal", "Higiene oral", "Sangrado de encías y halitosis", "4.50", "38", "500 ml", 6, 120, ("Sangrado de encías", "Mal aliento (halitosis)", "Dolor al masticar"), ("Infección respiratoria alta (IRA alta)",), "1.30"),
        _med("med-274", "Pasta dental sensibilidad", "Higiene oral", "Sensibilidad dental", "3.90", "60", "75 ml", 6, 120, ("Sensibilidad dental", "Dolor dental", "Dolor al masticar"), ("Infección respiratoria alta (IRA alta)",), "1.10"),
        _med("med-275", "AINE tópico (ketoprofeno) gel", "Antiinflamatorio tópico", "Dolor muscular", "10.50", "18", "50 g", 15, 120, ("Dolor muscular (mialgia)", "Dolor localizado con presión", "Limitación de movilidad"), ("Tendinitis (p. ej., manguito rotador)",), "3.60"),
        _med("med-276", "Calcetines compresivos", "Dispositivo", "Edema de piernas", "18.50", "12", "1 par", 18, 120, ("Edema de piernas", "Dolor en pantorrilla", "Calor/hinchazón en una pierna"), ("Trombosis venosa profunda (TVP)", "Insuficiencia cardiaca"), "6.80"),
        _med("med-277", "Antiinflamatorio oral (naproxeno)", "Antiinflamatorio", "Dolor articular", "4.90", "30", "20 comprimidos", 16, 120, ("Dolor articular (artralgia)", "Inflamación articular", "Dolor"), ("Osteoartrosis (artrosis)",), "2.10"),
        _med("med-278", "Parche analgésico", "Tópico", "Dolor localizado", "9.20", "18", "5 parches", 12, 120, ("Dolor localizado con presión", "Dolor muscular (mialgia)", "Limitación de movilidad"), ("Cervicalgia", "Lumbalgia mecánica"), "3.30"),
        _med("med-279", "Terapia frío/calor (pack)", "Dispositivo", "Dolor muscular y edema", "11.90", "12", "1 unidad", 12, 120, ("Edema (hinchazón)", "Dolor muscular (mialgia)", "Dolor localizado con presión"), ("Esguince de tobillo", "Lumbalgia mecánica"), "4.40"),
        _med("med-280", "Antiinflamatorio para artritis (ejemplo)", "Reumatología", "Dolor articular crónico (ejemplo)", "12.50", "10", "30 comprimidos", 18, 120, ("Dolor articular (artralgia)", "Rigidez articular", "Inflamación articular"), ("Artritis reumatoide",), "4.70"),

        # --- Piel / Alergia / Otros extra (281-300) ---
        _med("med-281", "Hidrocortisona crema 1%", "Corticoide tópico", "Dermatitis con picor", "3.50", "40", "30 g", 2, 120, ("Erupción cutánea (rash)", "Picor (prurito)", "Enrojecimiento (eritema)"), ("Dermatitis de contacto", "Dermatitis atópica"), "1.20"),
        _med("med-282", "Emoliente intenso", "Emoliente", "Piel seca con prurito", "9.20", "30", "500 ml", 0, 120, ("Piel seca (xerosis)", "Picor (prurito)", "Descamación"), ("Dermatitis atópica",), "3.10"),
        _med("med-283", "Crema barrera", "Tópico", "Irritación cutánea", "7.90", "26", "100 g", 0, 120, ("Enrojecimiento (eritema)", "Dolor/ardor al tacto", "Piel seca (xerosis)"), ("Dermatitis de contacto",), "2.80"),
        _med("med-284", "Antihistamínico tópico", "Antihistamínico tópico", "Picor localizado", "7.20", "22", "30 g", 0, 120, ("Picor (prurito)", "Urticaria (habones)", "Enrojecimiento (eritema)"), ("Urticaria", "Alergia"), "2.50"),
        _med("med-285", "Antihistamínico oral (fexofenadina)", "Antihistamínico", "Urticaria con picor", "7.40", "20", "20 comprimidos", 12, 120, ("Urticaria (habones)", "Picor (prurito)", "Enrojecimiento (eritema)"), ("Urticaria", "Alergia"), "2.70"),
        _med("med-286", "After-sun", "Tópico", "Irritación por sol", "8.10", "18", "200 ml", 2, 120, ("Enrojecimiento (eritema)", "Dolor/ardor al tacto", "Picor (prurito)"), ("Quemadura solar",), "2.90"),
        _med("med-287", "Protector solar SPF50", "Tópico", "Prevención de quemadura solar", "14.90", "22", "200 ml", 0, 120, ("Enrojecimiento (eritema)", "Dolor/ardor al tacto", "Cambios de coloración en piel"), ("Quemadura solar",), "5.60"),
        _med("med-288", "Antiséptico cutáneo", "Antiséptico", "Limpieza de heridas", "3.20", "80", "250 ml", 0, 120, ("Heridas que no cicatrizan", "Dolor/ardor al tacto", "Enrojecimiento (eritema)"), ("Celulitis bacteriana (infección de piel y partes blandas)",), "1.10"),
        _med("med-289", "Crema antibiótica (ejemplo)", "Antibiótico tópico", "Infección cutánea leve (ejemplo)", "8.90", "14", "15 g", 2, 120, ("Enrojecimiento (eritema)", "Dolor/ardor al tacto", "Hinchazón facial"), ("Celulitis bacteriana (infección de piel y partes blandas)",), "3.30"),
        _med("med-290", "Gel aloe vera", "Tópico", "Irritación y prurito", "5.60", "35", "250 ml", 0, 120, ("Picor (prurito)", "Enrojecimiento (eritema)", "Piel seca (xerosis)"), ("Dermatitis de contacto",), "1.80"),
        _med("med-291", "Champú anticaspa", "Dermocosmética", "Descamación y picor cuero cabelludo", "9.80", "20", "250 ml", 12, 120, ("Descamación", "Picor (prurito)", "Piel seca (xerosis)"), ("Dermatitis seborreica", "Dermatitis"), "3.20"),
        _med("med-292", "Crema para eczema", "Tópico", "Eczema con prurito", "10.20", "18", "50 g", 2, 120, ("Picor (prurito)", "Erupción cutánea (rash)", "Descamación"), ("Dermatitis atópica",), "3.60"),
        _med("med-293", "Gel para picaduras", "Tópico", "Picor por picadura", "6.20", "28", "30 g", 0, 120, ("Picor (prurito)", "Enrojecimiento (eritema)", "Urticaria (habones)"), ("Picadura",), "2.10"),
        _med("med-294", "Repelente de insectos", "Prevención", "Prevención de picaduras", "11.50", "30", "100 ml", 2, 120, ("Picor (prurito)", "Urticaria (habones)", "Enrojecimiento (eritema)"), ("Picadura",), "4.10"),
        _med("med-295", "Gel hidroalcohólico", "Higiene", "Higiene de manos (ejemplo)", "2.40", "200", "100 ml", 0, 120, ("Malestar general", "Fiebre", "Tos"), ("COVID-19", "Gripe (influenza)"), "0.80"),
        _med("med-296", "Tiras nasales", "Dispositivo", "Congestión nasal nocturna", "6.90", "26", "10 tiras", 12, 120, ("Congestión nasal", "Dificultad para respirar al acostarse", "Insomnio"), ("Rinitis alérgica", "Resfriado común"), "2.40"),
        _med("med-297", "Humidificador (ejemplo)", "Dispositivo", "Sequedad e irritación de garganta", "29.90", "6", "1 unidad", 0, 120, ("Dolor de garganta", "Boca seca (xerostomía)", "Tos seca"), ("Infección respiratoria alta (IRA alta)",), "10.50"),
        _med("med-298", "Gel para labios", "Tópico", "Sequedad y grietas", "4.20", "55", "10 g", 0, 120, ("Piel seca (xerosis)", "Dolor/ardor al tacto", "Descamación"), ("Dermatitis de contacto",), "1.40"),
        _med("med-299", "Crema manos reparadora", "Dermocosmética", "Piel seca y fisuras", "6.20", "40", "50 g", 0, 120, ("Piel seca (xerosis)", "Descamación", "Dolor/ardor al tacto"), ("Dermatitis de contacto",), "2.10"),
        _med("med-300", "Bálsamo respiratorio infantil", "Tópico", "Congestión y tos en resfriado", "7.10", "24", "50 g", 2, 12, ("Congestión nasal", "Tos", "Dolor de garganta"), ("Resfriado común", "Infección respiratoria alta (IRA alta)"), "2.30"),
    ]